### ISSUE TITLE
Bot can read but not respond to facebook messages? 

### ISSUE THREAD

**Issue by davidawad** [kimberli/hubot-messenger#3]
This is the only way to make a hubot that can listen and respond to posts on facebook messenger as a regular user. Being able to include hubot in group chats is HUGE. PLEASE don't give up on this project!!! But more importantly I wanted to ask about a specific issue that I'm having.

It looks like the bot is able to see messages but it doesn't respond anymore? When running it on a facebook page, the shell prints out all of the facebook messages it's getting, it looks like the bot just doesn't respond. Does this project still work for you? It's entirely possible this is limited to me. 

Also, thanks for making this!! I personally think it's necessary and it almost works perfectly!

**Comment by kimberli** [comment]
To be honest I don't quite have the bandwidth to maintain this. But I'll
look into your issue and get back to you by tonight or tomorrow!

**Comment by kimberli** [comment]
Oops, sorry for the late response. I just got it up and running again, and everything seems to be working fine. Maybe try and make sure your hubot rules are defined correctly? (e.g. `robot.hear` vs `robot.respond`).

**Comment by davidawad** [comment]
that was it, sorry for the super late reply. Really stupid on my part. 

Does this thing have the capacity to send individuals messages based on messenger id ? ?
